[package]
name = "contracts"
version = "0.1.0"

[dependencies]
starknet = ">=2.6.3"

[[target.starknet-contract]]
sierra = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.23.0" }

[scripts]
test = "snforge test"
